### ISSUE TITLE
Transaction stuck on PENDING

### ISSUE THREAD

**Issue by damanic** [dennisreimann/btcpayserver#16]
A outgoing payment from LNBANK is still showing as PENDING even though the attempt expired over 18 hours ago.

The balance shown in the LNBANK account has been reduced by the pending transaction value, so the funds are effectively locked.  

Regardless of the reason for the failed payment attempt, one would expect LNBANK to show the transaction as failed/expired and restore access to the funds.  

How best to restore/correct ?

Screenshots:

![image](https://user-images.githubusercontent.com/5227303/169171004-2657e2fd-dbef-46ad-a30a-ce3ceb36f6fb.png)
![image](https://user-images.githubusercontent.com/5227303/169171075-544992fd-c032-4dd9-b709-8e6a1030a82a.png)

LNBANK: v1.2.1.0 
BTCPAY: v1.5.2.0

**Comment by dennisreimann** [comment]
What is the actual state of the payment? (what do LND or Core Lightning, depending on what the underlying node is, report?)

Did the payment fail or succeed?

**Comment by damanic** [comment]
LND

There is no record of a transaction being sent in RTL.  

The payment failed.

**Comment by damanic** [comment]
UPDATE

Checking LNBank now.  It has been updated to CANCELLED.

What determines the time delay?

**Comment by dennisreimann** [comment]
> What determines the time delay? > 18 hours is a long time to wait after a failed payment attempt.

It doesn't have to immediately fail. An edge case here can be a hold invoice, which is paid from your side and hence needs to be handled as paid — it won't expire anymore. For those there are two outcomes:
- It gets settled when the receiver confirms it or 
- it gets cancelled when the receiver cancels it.

Meanwhile it is pending, but it cannot expire because it has already been paid on your end.

But for your actual problem: So the balance has been added to your LNbank account again and now the state matches the state underlying node?

**Comment by damanic** [comment]
The balance shown in LNBank has been restored to balance prior to payment attempt.

Your edge case was spot on.  It was a Hold invoice from Boltz - which is new to me!

So it appears LNBank handled itself correctly - no issue.  

Thanks for taking look.
